### ISSUE TITLE
RFE: mark the LSM hook structure as read only post-init

### ISSUE THREAD

**Issue by pcmoore** [SELinuxProject/selinux-kernel#15]
See the Openwall Kernel Hardening archive patchset for details.

* http://www.openwall.com/lists/kernel-hardening/2016/02/17/14

**Comment by garyttierney** [comment]
I think we can also do this for `selinux_nf_ops` https://github.com/SELinuxProject/selinux-kernel/blob/next/security/selinux/hooks.c#L6380.  Based on Kees' patch it should be as simple as using the `__ro_after_init` macro to add these declarations to the `.data..ro_after_init` section.

**Comment by stephensmalley** [comment]
Per the discussion on the lists, the hook ops list structure could be modified after init by the core NF code, so we can't do it for those.  Otherwise, this is/will be addressed by:
https://www.mail-archive.com/selinux@tycho.nsa.gov/msg03939.html
https://www.mail-archive.com/selinux@tycho.nsa.gov/msg03940.html
https://www.mail-archive.com/selinux@tycho.nsa.gov/msg03941.html
