### ISSUE TITLE
RFE: support IP_PASSSEC and SO_PASSSEC on both datagram and stream sockets

### ISSUE THREAD

**Issue by pcmoore** [SELinuxProject/selinux-kernel#17]
Support SOL_IP/IP_PASSSEC and SOL_SOCKET/SO_PASSSEC for both datagram and stream sockets.

**Comment by stephensmalley** [comment]
Sorry, what does this mean?

**Comment by pcmoore** [comment]
My apologies, those title changes sure made a mess of the history for little benefit.

Anyway, I believe the original intent of this request was to support a common method of requesting network peer label information across TCP/UDP.  I haven't looked into this at all, but it seemed like a reasonable request so I wanted to carry it over from the wiki todo list.  If someone wants to look at it and rule it out as a silly request, that's fine by me.

**Comment by stephensmalley** [comment]
We have SO_PEERSEC for TCP/stream, and IP_PASSSEC / SCM_SECURITY for UDP/datagram.
IMHO, that's correct. No need to support anything more.
The only request we've ever had for SCM_SECURITY support on stream was for Unix/local sockets, and that was from systemd, and they ultimately realized that they didn't need/want it after all - they switched to using SO_PEERSEC.  We did end up adding support for SCM_SECURITY for Unix/local stream sockets, because it was trivial to support, but I don't really see the point for TCP and I'm not sure it is trivial there.

**Comment by pcmoore** [comment]
Fair enough.
