### ISSUE TITLE
Enabling SELinux peer labeling

### ISSUE THREAD

**Issue by JayJay-K** [SELinuxProject/selinux-kernel#60]
I'm struggling with peer labeling in SCTP
I saw content "https://www.kernel.org/doc/html/v4.18/security/SELinux-sctp.html#sctp-peer-labeling".
It says "1. If peer labeling is not enabled, then the peer context will always be SECINITSID_UNLABELED (unlabeled_t in Reference Policy)."

In my understanding 'peer labeling' can be enabled or disabled in linux system.
Can I ask how to enable 'peer labeling' in linux system?
It's hard to find a way to do in the internet.

**Comment by JayJay-K** [comment]
No, I still have problem.
I'm not familiar with here. So I just wondered whether I can ask it here or not.
Could you please check my question?

In detailed, I met a SELinux error in SCTP association (re-association).
with scontext = unlabeled_t, tcontext=unlabed_t, type=sctp_socket, class=association.
I hope to know what is a right way to resolve this problem. candidates are;
  1. Just add SELinux allow policy.
  2. Enable 'peer labeling'. (I assumed this problem occur, because peer-labeling is disabled)
What is a right way?  If answer is number '2', how can I enable peer labeling?
(It runs on the container environment, OCP)

**Comment by WOnder93** [comment]
Oh, SCTP... That sounds like you're actually hitting a kernel bug that me and Xin Long tried to fix with [1] (or some variant of it). However, the patches needed some rework and I got sidetracked with other things, so the bug is not fixed yet... Good news is that I recently switched my attention back to this bug and am currently working on finalizing the proper fix.

[1] https://lore.kernel.org/selinux/cover.1635854268.git.lucien.xin@gmail.com/T/

**Comment by JayJay-K** [comment]
Thank you for information.
Additionally, may I have some workaround to resolve this problem before fixing it?
I hope to know expert's opinion what is the best way to avoid the error in current kernel version.

**Comment by JayJay-K** [comment]
Thank you for your information.
Additionally, may I ask you some workaround for the problem before fix it?
I hope to know expert's opinion what is the best way to avoid it with current version. :-)

Now, I handle it in the container environment. (OCP with kubernetes)
And a 'host server' is not my area, so I can't add SELinux allow rule to the host server.
(e.g. "allow unlabeled_t unlabeled_t:sctp_socket association")

So, I'm searching for 'selinuxOptions' in the 'securityContext' to configure pods.
Can I add SELinux allow rule to pods with selinuxOptions? and how?
I'm checking following links, but it's hard to find exact way.
 - https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#selinuxoptions-v1-core
 - https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
Could you give me an advice for it, or another way to handle this problem?

**Comment by pcmoore** [comment]
Hi @JayJay-K, unfortunately I don't have much experience running OCP and/or K8s so I'm not sure I can be of much help there, I'm sorry :/

**Comment by WOnder93** [comment]
@JayJay-K One of our engineers created a configuration that applies a workaround for this exact issue (via a SELinux policy module) and he made it available on GitHub:
https://github.com/yuvalk/ocp-security/blob/master/sctp/selinux_custom.deployment.yaml

Use at your own risk :)

**Comment by JayJay-K** [comment]
Thank you @WOnder93.  I hope to add one more question.
How can I be sure that my error occur because of the kernel bug you mentioned?

Actually, I'm not familiar with SCTP, so it was hard to understand exact meaning of following:
[1] https://lore.kernel.org/selinux/cover.1635854268.git.lucien.xin@gmail.com/T/

I met following error when SCTP socket do assoc again (re-assoc?) with different SID:
type=AVC msg=audit(1644235060.178:460343): avc:  denied  { association } for  pid=174 comm="ksoftirqd/20" laddr=2001:db8:b03:215::27:9901 lport=36422 faddr=2001:db8:b05:3001:222:0:24:4 fport=36422 scontext=system_u:object_r:unlabeled_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=sctp_socket permissive=0

Could you please let me know a way that I'm sure my error occur because of the kernel bug, if you know?

**Comment by WOnder93** [comment]
@JayJay-K Yeah, it's pretty complicated stuff... But I'd say you can quite safely assume that you are running into this bug. I don't see any other way you could get it (and you're also not the first one to hit it on OCP).

Actually you may find a bit of useful information about the bug in the relevant RH bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=2048251

I tried to TL;DR the bug in the Doc Text and there is a more detailed low-level explanation in comment 36. There is also a crude reproducer attached, but be aware that it has a race condition and sometimes fails on its own. It also hits another related bug (https://bugzilla.redhat.com/show_bug.cgi?id=2015525), which is fixed by the same set of kernel patches.
